language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    - tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+
    
script:
   - ./gradlew build connectedCheck
   - chmod +x ./gradlew
