language: android
jdk: oraclejdk8
sudo: required
env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=x86

android:
  components:
    - tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

  licenses:
    - android-sdk-license-.+
    
before_install:
   - chmod +x gradlew

script:
   - ./gradlew build connectedCheck
   
